"""initial_tables

Revision ID: 6c8fd5ab903d
Revises: 
Create Date: 2026-08-23 19:56:35.013900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c8fd5ab903d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False, comment='Telegram user ID who owns this task'),
    sa.Column('title', sa.String(length=500), nullable=False, comment='Short task description'),
    sa.Column('description', sa.Text(), nullable=True, comment='Optional detailed description or notes'),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='task_status', native_enum=False), server_default='pending', nullable=False, comment='Current task lifecycle state'),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='task_priority', native_enum=False), server_default='medium', nullable=False, comment='Task importance level'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True, comment='Optional deadline or scheduled time (UTC)'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When the task was completed'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_telegram_user_id'), 'tasks', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_telegram_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_table('tasks')
    # ### end Alembic commands ###
