"""Add long term memory

Revision ID: be14157ce529
Revises: 230b8d52b7e7
Create Date: 2026-08-26 19:01:10.000472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be14157ce529'
down_revision: Union[str, None] = '230b8d52b7e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('long_term_memories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False, comment='Telegram user ID who owns this memory'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='Category of the memory (e.g. identity, preference, habit, other)'),
    sa.Column('fact', sa.Text(), nullable=False, comment='The actual fact/memory stored'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_long_term_memories_category'), 'long_term_memories', ['category'], unique=False)
    op.create_index(op.f('ix_long_term_memories_telegram_user_id'), 'long_term_memories', ['telegram_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_long_term_memories_telegram_user_id'), table_name='long_term_memories')
    op.drop_index(op.f('ix_long_term_memories_category'), table_name='long_term_memories')
    op.drop_table('long_term_memories')
    # ### end Alembic commands ###
